# Heart Failure Data Analysis

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [4]:
#reading the dataframe
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1.0,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1.0,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1.0,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1.0,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0.0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1.0,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0.0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0.0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1.0,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1.0,1,285,0

In [5]:
df.shape

(299, 13)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       298 non-null    float64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    str
 12  DEATH_EVENT               298 non-null    str
dtypes: float64(4), int64(7), str(2)
memory usage: 30.5 KB

In [7]:
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1.0,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1.0,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1.0,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1.0,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0.0,0,8,1

In [8]:
df.tail()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
294,62.0,0,61,1,38,1,155000.0,1.1,143,1.0,1,270,0
295,55.0,0,1820,0,38,0,270000.0,1.2,139,0.0,0,271,0
296,45.0,0,2060,1,60,0,742000.0,0.8,138,0.0,0,278,0
297,45.0,0,2413,0,38,0,140000.0,1.4,140,1.0,1,280,0
298,50.0,0,196,0,45,0,395000.0,1.6,136,1.0,1,285,0

In [9]:
df.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,298.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.647651,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478506,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000

In [10]:
#value counts
df["diabetes"].value_counts()

diabetes
0    174
1    125
Name: count, dtype: int64

In [11]:
df["sex"].value_counts()

sex
1.0    193
0.0    105
Name: count, dtype: int64

In [12]:
df["DEATH_EVENT"].value_counts()

DEATH_EVENT
0    202
1     95
?      1
Name: count, dtype: int64

In [13]:
#new column addition
df["Age_Group"] = np.where(df["age"] >= 60,
                           "Senior",
                           "Adult")

In [14]:
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,Age_Group
0,75.0,0,582,0,20,1,265000.00,1.9,130,1.0,0,4,1,Senior
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1.0,0,6,1,Adult
2,65.0,0,146,0,20,0,162000.00,1.3,129,1.0,1,7,1,Senior
3,50.0,1,111,0,20,0,210000.00,1.9,137,1.0,0,7,1,Adult
4,65.0,1,160,1,20,0,327000.00,2.7,116,0.0,0,8,1,Senior

In [15]:
df["Heart_Function"] = np.where(df["ejection_fraction"] >= 50,
                                "Normal",
                                "Reduced")

In [16]:
#Concatenation of DataFrames
df1 = df.iloc[:150]
df2 = df.iloc[150:]

In [17]:
combined = pd.concat([df1, df2])
combined.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,Age_Group,Heart_Function
0,75.0,0,582,0,20,1,265000.00,1.9,130,1.0,0,4,1,Senior,Reduced
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1.0,0,6,1,Adult,Reduced
2,65.0,0,146,0,20,0,162000.00,1.3,129,1.0,1,7,1,Senior,Reduced
3,50.0,1,111,0,20,0,210000.00,1.9,137,1.0,0,7,1,Adult,Reduced
4,65.0,1,160,1,20,0,327000.00,2.7,116,0.0,0,8,1,Senior,Reduced

In [18]:
patient_info = df[["age","sex"]]

medical_info = df[["diabetes","smoking"]]

In [19]:
horizontal = pd.concat([patient_info, medical_info], axis=1)

horizontal.head()

    age  sex  diabetes  smoking
0  75.0  1.0         0        0
1  55.0  1.0         0        0
2  65.0  1.0         0        1
3  50.0  1.0         0        0
4  65.0  0.0         1        0

In [20]:
#Merging DataFrames
patient = df[["age","sex"]].copy()
medical = df[["diabetes",
              "smoking",
              "DEATH_EVENT"]].copy()
patient["Patient_ID"] = range(1, len(patient)+1)

medical["Patient_ID"] = range(1, len(medical)+1)

In [21]:
merged = pd.merge(patient,
                  medical,
                  on="Patient_ID")
merged.head()

    age  sex  Patient_ID  diabetes  smoking DEATH_EVENT
0  75.0  1.0           1         0        0           1
1  55.0  1.0           2         0        0           1
2  65.0  1.0           3         0        1           1
3  50.0  1.0           4         0        0           1
4  65.0  0.0           5         1        0           1

In [22]:
#hierarchal indexing
hierarchy = df.set_index(["sex","DEATH_EVENT"])
hierarchy.head()

                  age  anaemia  creatinine_phosphokinase  diabetes  \
sex DEATH_EVENT
1.0 1            75.0        0                       582         0
    1            55.0        0                      7861         0
    1            65.0        0                       146         0
    1            50.0        1                       111         0
0.0 1            65.0        1                       160         1

                 ejection_fraction  high_blood_pressure  platelets  \
sex DEATH_EVENT
1.0 1                           20                    1  265000.00
    1                           38                    0  263358.03
    1                           20                    0  162000.00
    1                           20                    0  210000.00
0.0 1                           20                    0  327000.00

                 serum_creatinine  serum_sodium  smoking time Age_Group  \
sex DEATH_EVENT
1.0 1                         1.9           130        0    4    Senior
    1                         1.1           136        0    6     Adult
    1                         1.3           129        1    7    Senior
    1                         1.9           137        0    7     Adult
0.0 1                         2.7           116        0    8    Senior

                Heart_Function
sex DEATH_EVENT
1.0 1                  Reduced
    1                  Reduced
    1                  Reduced
    1                  Reduced
0.0 1                  Reduced

In [23]:
hierarchy.loc[1]

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,smoking,time,Age_Group,Heart_Function
DEATH_EVENT,,,,,,,,,,,,,
1,75.0,0,582,0,20,1,265000.00,1.9,130,0,4,Senior,Reduced
1,55.0,0,7861,0,38,0,263358.03,1.1,136,0,6,Adult,Reduced
1,65.0,0,146,0,20,0,162000.00,1.3,129,1,7,Senior,Reduced
1,50.0,1,111,0,20,0,210000.00,1.9,137,0,7,Adult,Reduced
1,90.0,1,47,0,40,1,204000.00,2.1,132,1,8,Senior,Reduced
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,52.0,0,190,1,38,0,382000.00,1.0,140,1,258,Adult,Reduced
0,63.0,1,103,1,35,0,179000.00,0.9,136,1,270,Senior,Reduced
0,62.0,0,61,1,38,1,155000.00,1.1,143,1,270,Senior,Reduced
0,45.0,0,2413,0,38,0,140000.00,1.4,140,1,280,Adult,Reduced
0,50.0,0,196,0,45,0,395000.00,1.6,136,1,285,Adult,Reduced

In [24]:
hierarchy.loc[0]

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,smoking,time,Age_Group,Heart_Function
DEATH_EVENT,,,,,,,,,,,,,
1,65.0,1,160,1,20,0,327000.00,2.7,116,0,8,Senior,Reduced
1,65.0,0,157,0,65,0,263358.03,1.5,138,0,10,Senior,Normal
0,49.0,1,80,0,30,1,427000.00,1.0,138,0,12,Adult,Reduced
1,70.0,1,125,0,25,1,237000.00,1.0,140,0,15,Senior,Reduced
1,48.0,1,582,1,55,0,87000.00,1.9,121,0,15,Adult,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,65.0,0,892,1,35,0,263358.03,1.1,142,0,256,Senior,Reduced
0,90.0,1,337,0,38,0,390000.00,0.9,144,0,256,Senior,Reduced
0,45.0,0,615,1,55,0,222000.00,0.8,141,0,257,Adult,Normal
0,55.0,0,1820,0,38,0,270000.00,1.2,139,0,271,Adult,Reduced
0,45.0,0,2060,1,60,0,742000.00,0.8,138,0,278,Adult,Normal

In [25]:
#series concatenation with keys
age = df["age"].head()

creatinine = df["serum_creatinine"].head()

In [26]:
series = pd.concat([age,
                    creatinine],
                   keys=["Age",
                         "Creatinine"])
series

Age         0    75.0
            1    55.0
            2    65.0
            3    50.0
            4    65.0
Creatinine  0     1.9
            1     1.1
            2     1.3
            3     1.9
            4     2.7
dtype: float64

In [27]:
#sorting
df.sort_values("age")

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,Age_Group,Heart_Function
269,40.0,0,582,1,35,0,222000.00,1.00,132,1.0,0,244,0,Adult,Reduced
232,40.0,1,129,0,35,0,255000.00,0.90,137,1.0,0,209,0,Adult,Reduced
180,40.0,0,478,1,30,0,303000.00,0.90,136,1.0,0,148,0,Adult,Reduced
242,40.0,0,90,0,35,0,255000.00,1.10,136,1.0,1,212,0,Adult,Reduced
248,40.0,0,624,0,35,0,301000.00,1.00,142,1.0,1,214,0,Adult,Reduced
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,90.0,1,60,1,50,0,226000.00,1.00,134,1.0,0,30,1,Senior,Normal
5,90.0,1,47,0,40,1,204000.00,2.10,132,1.0,1,8,1,Senior,Reduced
30,94.0,0,582,1,38,1,263358.03,1.83,134,1.0,0,27,1,Senior,Reduced
55,95.0,1,371,0,30,0,461000.00,2.00,132,1.0,0,50,1,Senior,Reduced
26,95.0,1,112,0,40,1,196000.00,1.00,138,0.0,0,24,1,Senior,Reduced

In [28]:
df.sort_values("age",
               ascending=False)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,Age_Group,Heart_Function
26,95.0,1,112,0,40,1,196000.00,1.00,138,0.0,0,24,1,Senior,Reduced
55,95.0,1,371,0,30,0,461000.00,2.00,132,1.0,0,50,1,Senior,Reduced
30,94.0,0,582,1,38,1,263358.03,1.83,134,1.0,0,27,1,Senior,Reduced
36,90.0,1,60,1,50,0,226000.00,1.00,134,1.0,0,30,1,Senior,Normal
5,90.0,1,47,0,40,1,204000.00,2.10,132,1.0,1,8,1,Senior,Reduced
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,40.0,0,244,0,45,1,275000.00,0.90,140,0.0,0,174,0,Adult,Reduced
248,40.0,0,624,0,35,0,301000.00,1.00,142,1.0,1,214,0,Adult,Reduced
206,40.0,1,101,0,40,0,226000.00,0.80,141,0.0,0,187,0,Adult,Reduced
269,40.0,0,582,1,35,0,222000.00,1.00,132,1.0,0,244,0,Adult,Reduced
180,40.0,0,478,1,30,0,303000.00,0.90,136,1.0,0,148,0,Adult,Reduced

In [29]:
#selecting columns
df[["age","diabetes","smoking"]]

      age  diabetes  smoking
0    75.0         0        0
1    55.0         0        0
2    65.0         0        1
3    50.0         0        0
4    65.0         1        0
..    ...       ...      ...
294  62.0         1        1
295  55.0         0        0
296  45.0         1        0
297  45.0         0        1
298  50.0         0        1

[299 rows x 3 columns]

In [30]:
#maximum
df.max(numeric_only=True)

age                             95.0
anaemia                          1.0
creatinine_phosphokinase      7861.0
diabetes                         1.0
ejection_fraction               80.0
high_blood_pressure              1.0
platelets                   850000.0
serum_creatinine                 9.4
serum_sodium                   148.0
sex                              1.0
smoking                          1.0
dtype: float64

In [31]:
#minimum
df.min(numeric_only=True)

age                            40.0
anaemia                         0.0
creatinine_phosphokinase       23.0
diabetes                        0.0
ejection_fraction              14.0
high_blood_pressure             0.0
platelets                   25100.0
serum_creatinine                0.5
serum_sodium                  113.0
sex                             0.0
smoking                         0.0
dtype: float64

In [32]:
#median
df.median(numeric_only=True)

age                             60.0
anaemia                          0.0
creatinine_phosphokinase       250.0
diabetes                         0.0
ejection_fraction               38.0
high_blood_pressure              0.0
platelets                   262000.0
serum_creatinine                 1.1
serum_sodium                   137.0
sex                              1.0
smoking                          0.0
dtype: float64

In [33]:
#standard deviation
df.std(numeric_only=True)

age                            11.894809
anaemia                         0.496107
creatinine_phosphokinase      970.287881
diabetes                        0.494067
ejection_fraction              11.834841
high_blood_pressure             0.478136
platelets                   97804.236869
serum_creatinine                1.034510
serum_sodium                    4.412477
sex                             0.478506
smoking                         0.467670
dtype: float64

In [34]:
#unique values
df["sex"].unique()

array([ 1.,  0., nan])

In [35]:
#cross relation ( crosstab ) 
pd.crosstab(df["diabetes"],
            df["DEATH_EVENT"])

DEATH_EVENT    0   1  ?
diabetes
0            117  55  1
1             85  40  0

In [36]:
#duplicate check
df.duplicated().sum()

np.int64(0)

In [37]:
#saving
df.to_csv("heart_failure_modified.csv",
          index=False)